### PR TITLE
Fixed Handler.

### PR DESCRIPTION
**Pull request by PEMapModder**
If you understand the code you copied, you wouldn't have written all that rubbish.

### CODE REVIEW

**Comment by Gamecrafter** [comment]
Guess I have some unlearning to do.

**Comment by caingaroo** [comment]
Um what dose the plugin do i dont see it add plugins and all it say is its advanced core plugin

**Comment by Gamecrafter** [comment]
Huh, I don't understand what you're trying to say.

**Comment by caingaroo** [comment]
Ignore what i seid, i ment was i dont understand what the plugin dose and the plugin loads but win i joined i automatically got kick and my server stoped

**Comment by Gamecrafter** [comment]
Oh, the plugin isn't finished yet. I'll fix it when I have time.

**Comment by caingaroo** [comment]
Ok wish i could make a plugin PHP to hard for me and i could never learn 😔, anyways can you notify me win your done!?

**Comment by Gamecrafter** [comment]
Just watch the plugin.

**Comment by caingaroo** [comment]
I have been watching since 3 days ago

**Comment by Gamecrafter** [comment]
No, like click on the watch button on the top. You'll be automatically notified when updates are made.

**Comment by caingaroo** [comment]
Ok, thanks for the help!

**Pull request merged**
